service:
  name: stripe-serverless
  app: stripe-serverless
  org: rangle.io

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 4242

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  tag:
    project: stripe-serverless
    createdBy: Douglas Petla

functions:
  index:
    handler: index.handler
    events:
      - http:
          path: /{any+}
          method: ANY
          cors:
            origin: "*"
